# Bag of Words and TF-IDF
Below, we'll look at three useful methods of vectorizing text.
- `CountVectorizer` - Bag of Words
- `TfidfTransformer` - TF-IDF values
- `TfidfVectorizer` - Bag of Words AND TF-IDF values

Let's first use an example from earlier and apply the text processing steps we saw in this lesson.

In [215]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\N12667\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\N12667\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\N12667\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [216]:
corpus = ["The first time you see The Second Renaissance it may look boring.",
        "Look at it at least twice and definitely watch part 2.",
        "It will change your view of the matrix.",
        "Are the human people the ones who started the war?",
        "Is AI a bad thing ?"]

corpus = ["The first time you see The Second Renaissance it may seem boring.",
        "Look at it at least twice and definitely look at part 2.",
        "It will change your view of the matrix.",
        "Are the human people the ones who started the war?",
        "Is AI a bad thing ?",
        "Moose moose moose schmoose"]

In [217]:
stop_words = stopwords.words("english")
lemmatizer = WordNetLemmatizer()

Use the skills you learned so far to create a function `tokenize` that takes in a string of text and applies the following:
- case normalization (convert to all lowercase)
- punctuation removal
- tokenization, lemmatization, and stop word removal using `nltk`

Feel free to refer back to previous sections to complete these steps!

In [218]:
def tokenize(text):
    # normalize case and remove punctuation
    text = re.sub(r"[^a-zA-Z0-9]", " ", text.lower())
    
    # tokenize text
    tokens = word_tokenize(text)
    
    # lemmatize and remove stop words
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]

    return tokens

[tokenize(s) for s in corpus]

[['first', 'time', 'see', 'second', 'renaissance', 'may', 'seem', 'boring'],
 ['look', 'least', 'twice', 'definitely', 'look', 'part', '2'],
 ['change', 'view', 'matrix'],
 ['human', 'people', 'one', 'started', 'war'],
 ['ai', 'bad', 'thing'],
 ['moose', 'moose', 'moose', 'schmoose']]

# `CountVectorizer` (Bag of Words)

In [219]:
from sklearn.feature_extraction.text import CountVectorizer

# initialize count vectorizer object
vect = CountVectorizer(tokenizer=tokenize)

In [220]:
# get counts of each token (word) in text data
X = vect.fit_transform(corpus)

In [221]:
# convert sparse matrix to numpy array to view
import pandas as pd

def vect_to_df(X, vect):
    keys = list(vect.vocabulary_.keys())
    values = vect.vocabulary_.values()
    mapper = {keys[i]: vect.vocabulary_[keys[i]] for i in values} 
    cols = [key for key, value in sorted(mapper.items(), key=lambda kv: kv[1])] # sort by value
    return pd.DataFrame(X.toarray(), columns=cols)

vect_to_df(X, vect)

,2,ai,bad,boring,change,definitely,first,human,least,look,...,schmoose,second,see,seem,started,thing,time,twice,view,war
0,0,0,0,1,0,0,1,0,0,0,...,0,1,1,1,0,0,1,0,0,0
1,1,0,0,0,0,1,0,0,1,2,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
4,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [222]:
# view token vocabulary and counts
vect.vocabulary_

{'first': 6,
 'time': 23,
 'see': 19,
 'second': 18,
 'renaissance': 16,
 'may': 11,
 'seem': 20,
 'boring': 3,
 'look': 9,
 'least': 8,
 'twice': 24,
 'definitely': 5,
 'part': 14,
 '2': 0,
 'change': 4,
 'view': 25,
 'matrix': 10,
 'human': 7,
 'people': 15,
 'one': 13,
 'started': 21,
 'war': 26,
 'ai': 1,
 'bad': 2,
 'thing': 22,
 'moose': 12,
 'schmoose': 17}

In [223]:
vect_to_df(X, vect)

,2,ai,bad,boring,change,definitely,first,human,least,look,...,schmoose,second,see,seem,started,thing,time,twice,view,war
0,0,0,0,1,0,0,1,0,0,0,...,0,1,1,1,0,0,1,0,0,0
1,1,0,0,0,0,1,0,0,1,2,...,0,0,0,0,0,0,0,1,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,1
4,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

# `TfidfTransformer`

In [224]:
from sklearn.feature_extraction.text import TfidfTransformer

# initialize tf-idf transformer object
transformer = TfidfTransformer(smooth_idf=False)

In [225]:
# use counts from count vectorizer results to compute tf-idf values
tfidf = transformer.fit_transform(X)

In [226]:
# convert sparse matrix to numpy array to view
vect_to_df(tfidf, vect)

,2,ai,bad,boring,change,definitely,first,human,least,look,...,schmoose,second,see,seem,started,thing,time,twice,view,war
0,0.000000,0.00000,0.00000,0.353553,0.00000,0.000000,0.353553,0.000000,0.000000,0.000000,...,0.000000,0.353553,0.353553,0.353553,0.000000,0.00000,0.353553,0.000000,0.00000,0.000000
1,0.333333,0.00000,0.00000,0.000000,0.00000,0.333333,0.000000,0.000000,0.333333,0.666667,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.333333,0.00000,0.000000
2,0.000000,0.00000,0.00000,0.000000,0.57735,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.57735,0.000000
3,0.000000,0.00000,0.00000,0.000000,0.00000,0.000000,0.000000,0.447214,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.447214,0.00000,0.000000,0.000000,0.00000,0.447214
4,0.000000,0.57735,0.57735,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.57735,0.000000,0.000000,0.00000,0.000000
5,0.000000,0.00000,0.00000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.316228,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000

# `TfidfVectorizer`
`TfidfVectorizer` = `CountVectorizer` + `TfidfTransformer`

In [227]:
from sklearn.feature_extraction.text import TfidfVectorizer

# initialize tf-idf vectorizer object
vectorizer = TfidfVectorizer(tokenizer=tokenize)

In [228]:
# compute bag of word counts and tf-idf values
X = vectorizer.fit_transform(corpus)

In [229]:
# convert sparse matrix to numpy array to view
vect_to_df(X, vectorizer).T

                    0         1        2         3        4         5
2            0.000000  0.333333  0.00000  0.000000  0.00000  0.000000
ai           0.000000  0.000000  0.00000  0.000000  0.57735  0.000000
bad          0.000000  0.000000  0.00000  0.000000  0.57735  0.000000
boring       0.353553  0.000000  0.00000  0.000000  0.00000  0.000000
change       0.000000  0.000000  0.57735  0.000000  0.00000  0.000000
definitely   0.000000  0.333333  0.00000  0.000000  0.00000  0.000000
first        0.353553  0.000000  0.00000  0.000000  0.00000  0.000000
human        0.000000  0.000000  0.00000  0.447214  0.00000  0.000000
least        0.000000  0.333333  0.00000  0.000000  0.00000  0.000000
look         0.000000  0.666667  0.00000  0.000000  0.00000  0.000000
matrix       0.000000  0.000000  0.57735  0.000000  0.00000  0.000000
may          0.353553  0.000000  0.00000  0.000000  0.00000  0.000000
moose        0.000000  0.000000  0.00000  0.000000  0.00000  0.948683
one          0.000000  0.000000  0.00000  0.447214  0.00000  0.000000
part         0.000000  0.333333  0.00000  0.000000  0.00000  0.000000
people       0.000000  0.000000  0.00000  0.447214  0.00000  0.000000
renaissance  0.353553  0.000000  0.00000  0.000000  0.00000  0.000000
schmoose     0.000000  0.000000  0.00000  0.000000  0.00000  0.316228
second       0.353553  0.000000  0.00000  0.000000  0.00000  0.000000
see          0.353553  0.000000  0.00000  0.000000  0.00000  0.000000
seem         0.353553  0.000000  0.00000  0.000000  0.00000  0.000000
started      0.000000  0.000000  0.00000  0.447214  0.00000  0.000000
thing        0.000000  0.000000  0.00000  0.000000  0.57735  0.000000
time         0.353553  0.000000  0.00000  0.000000  0.00000  0.000000
twice        0.000000  0.333333  0.00000  0.000000  0.00000  0.000000
view         0.000000  0.000000  0.57735  0.000000  0.00000  0.000000
war          0.000000  0.000000  0.00000  0.447214  0.00000  0.000000